
import { PatternData } from './types/patternTypes';
import { v4 as uuidv4 } from 'uuid';
import { ensureDateString } from '@/utils/dateConverter';

// Create initial patterns with correct property types
export const initialPatterns: PatternData[] = [
  {
    id: uuidv4(),
    symbol: 'AAPL',
    timeframe: 'daily',
    patternType: 'Double Bottom',
    direction: 'bullish',
    createdAt: new Date().toISOString(),
    entryPrice: 180.25,
    targetPrice: 195.50,
    confidenceScore: 85,
    status: 'active',
    channelType: 'ascending',
    emaPattern: 'allBullish',
    supportLevel: 175.80,
    resistanceLevel: 185.20,
    trendlineBreak: true,
    volumeConfirmation: true,
    targetPercent: 8.5,
    predictedBreakoutCandles: 3
  },
  {
    id: uuidv4(),
    symbol: 'MSFT',
    timeframe: 'daily',
    patternType: 'Bull Flag',
    direction: 'bullish',
    createdAt: new Date().toISOString(),
    entryPrice: 340.50,
    targetPrice: 365.75,
    confidenceScore: 78,
    status: 'active',
    channelType: 'ascending',
    emaPattern: '7over50',
    supportLevel: 335.20,
    resistanceLevel: 345.60,
    trendlineBreak: false,
    volumeConfirmation: true,
    targetPercent: 7.4,
    predictedBreakoutCandles: 5
  },
  {
    id: uuidv4(),
    symbol: 'GOOGL',
    timeframe: 'daily',
    patternType: 'Ascending Triangle',
    direction: 'bullish',
    createdAt: new Date().toISOString(),
    entryPrice: 125.75,
    targetPrice: 138.20,
    confidenceScore: 82,
    status: 'active',
    channelType: 'ascending',
    emaPattern: 'allBullish',
    supportLevel: 122.30,
    resistanceLevel: 128.50,
    trendlineBreak: true,
    volumeConfirmation: true,
    targetPercent: 9.9,
    predictedBreakoutCandles: 4
  },
  {
    id: uuidv4(),
    symbol: 'AMZN',
    timeframe: 'daily',
    patternType: 'Cup and Handle',
    direction: 'bullish',
    createdAt: new Date().toISOString(),
    entryPrice: 130.25,
    targetPrice: 145.80,
    confidenceScore: 76,
    status: 'active',
    channelType: 'horizontal',
    emaPattern: '7over50',
    supportLevel: 127.50,
    resistanceLevel: 133.40,
    trendlineBreak: false,
    volumeConfirmation: true,
    targetPercent: 11.9,
    predictedBreakoutCandles: 7
  },
  {
    id: uuidv4(),
    symbol: 'TSLA',
    timeframe: 'daily',
    patternType: 'Head and Shoulders',
    direction: 'bearish',
    createdAt: new Date().toISOString(),
    entryPrice: 245.30,
    targetPrice: 210.50,
    confidenceScore: 72,
    status: 'active',
    channelType: 'descending',
    emaPattern: 'allBearish',
    supportLevel: 235.80,
    resistanceLevel: 255.20,
    trendlineBreak: true,
    volumeConfirmation: false,
    targetPercent: -14.2,
    predictedBreakoutCandles: 6
  },
  {
    id: uuidv4(),
    symbol: 'NVDA',
    timeframe: 'daily',
    patternType: 'Double Top',
    direction: 'bearish',
    createdAt: new Date().toISOString(),
    entryPrice: 420.75,
    targetPrice: 380.20,
    confidenceScore: 68,
    status: 'active',
    channelType: 'descending',
    emaPattern: '7under50',
    supportLevel: 410.30,
    resistanceLevel: 430.50,
    trendlineBreak: false,
    volumeConfirmation: true,
    targetPercent: -9.6,
    predictedBreakoutCandles: 5
  },
  {
    id: uuidv4(),
    symbol: 'META',
    timeframe: 'daily',
    patternType: 'Inverse Head and Shoulders',
    direction: 'bullish',
    createdAt: new Date().toISOString(),
    entryPrice: 295.40,
    targetPrice: 325.80,
    confidenceScore: 79,
    status: 'active',
    channelType: 'ascending',
    emaPattern: 'allBullish',
    supportLevel: 290.20,
    resistanceLevel: 300.60,
    trendlineBreak: true,
    volumeConfirmation: true,
    targetPercent: 10.3,
    predictedBreakoutCandles: 4
  },
  {
    id: uuidv4(),
    symbol: 'AMD',
    timeframe: 'daily',
    patternType: 'Symmetrical Triangle',
    direction: 'bullish',
    createdAt: new Date().toISOString(),
    entryPrice: 110.25,
    targetPrice: 125.50,
    confidenceScore: 71,
    status: 'active',
    channelType: 'horizontal',
    emaPattern: 'mixed',
    supportLevel: 105.80,
    resistanceLevel: 115.20,
    trendlineBreak: false,
    volumeConfirmation: true,
    targetPercent: 13.8,
    predictedBreakoutCandles: 6
  },
  {
    id: uuidv4(),
    symbol: 'INTC',
    timeframe: 'daily',
    patternType: 'Descending Triangle',
    direction: 'bearish',
    createdAt: new Date().toISOString(),
    entryPrice: 35.60,
    targetPrice: 30.20,
    confidenceScore: 65,
    status: 'active',
    channelType: 'descending',
    emaPattern: 'allBearish',
    supportLevel: 34.30,
    resistanceLevel: 37.50,
    trendlineBreak: false,
    volumeConfirmation: false,
    targetPercent: -15.2,
    predictedBreakoutCandles: 7
  },
  {
    id: uuidv4(),
    symbol: 'MU',
    timeframe: 'daily',
    patternType: 'Bear Flag',
    direction: 'bearish',
    createdAt: new Date().toISOString(),
    entryPrice: 75.40,
    targetPrice: 65.80,
    confidenceScore: 69,
    status: 'active',
    channelType: 'descending',
    emaPattern: '7under50',
    supportLevel: 73.20,
    resistanceLevel: 78.60,
    trendlineBreak: true,
    volumeConfirmation: true,
    targetPercent: -12.7,
    predictedBreakoutCandles: 5
  }
];

// No duplicate export - just use the initialPatterns from above
