-- Create market_data_cache table
CREATE TABLE IF NOT EXISTS market_data_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key TEXT NOT NULL,
    symbol TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    open DECIMAL(12,4) NOT NULL,
    high DECIMAL(12,4) NOT NULL,
    low DECIMAL(12,4) NOT NULL,
    close DECIMAL(12,4) NOT NULL,
    volume BIGINT NOT NULL,
    index INTEGER NOT NULL,
    ema7 DECIMAL(12,4),
    ema20 DECIMAL(12,4),
    ema50 DECIMAL(12,4),
    ema100 DECIMAL(12,4),
    ema200 DECIMAL(12,4),
    rsi14 DECIMAL(12,4),
    atr14 DECIMAL(12,4),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on cache_key for faster queries
CREATE INDEX IF NOT EXISTS idx_market_data_cache_key ON market_data_cache(cache_key);

-- Create market_data_metadata table
CREATE TABLE IF NOT EXISTS market_data_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key TEXT NOT NULL UNIQUE,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    source TEXT NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_delayed BOOLEAN NOT NULL DEFAULT FALSE,
    request_duration INTEGER,
    retry_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on cache_key for faster queries
CREATE INDEX IF NOT EXISTS idx_market_data_metadata_key ON market_data_metadata(cache_key);

-- Create detected_patterns table if it doesn't exist already
CREATE TABLE IF NOT EXISTS detected_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    pattern_type TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    confidence_score INTEGER NOT NULL,
    multi_timeframe_confirmation BOOLEAN NOT NULL DEFAULT FALSE,
    entry_price DECIMAL(12,4) NOT NULL,
    target_price DECIMAL(12,4) NOT NULL,
    stop_loss DECIMAL(12,4) NOT NULL,
    risk_reward_ratio DECIMAL(8,2) NOT NULL,
    detected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    pattern_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on symbol for faster queries
CREATE INDEX IF NOT EXISTS idx_detected_patterns_symbol ON detected_patterns(symbol);
CREATE INDEX IF NOT EXISTS idx_detected_patterns_timeframe ON detected_patterns(timeframe);
CREATE INDEX IF NOT EXISTS idx_detected_patterns_detected_at ON detected_patterns(detected_at);

-- Enable Row Level Security (RLS) with default deny
ALTER TABLE market_data_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_data_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE detected_patterns ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users to read data
CREATE POLICY "Allow authenticated users to read market_data_cache"
ON market_data_cache FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated users to read market_data_metadata"
ON market_data_metadata FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated users to read detected_patterns"
ON detected_patterns FOR SELECT
TO authenticated
USING (true);

-- Create policy for anon users to read only detected_patterns
CREATE POLICY "Allow anon users to read detected_patterns"
ON detected_patterns FOR SELECT
TO anon
USING (true); 