-- Add missing columns to backtest_results table if they don't exist
DO $$
BEGIN
    -- Check if symbol column exists in backtest_results table
    IF NOT EXISTS (
        SELECT FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'backtest_results'
        AND column_name = 'symbol'
    ) THEN
        ALTER TABLE backtest_results ADD COLUMN symbol TEXT;
    END IF;

    -- Check if pattern_type column exists
    IF NOT EXISTS (
        SELECT FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'backtest_results'
        AND column_name = 'pattern_type'
    ) THEN
        ALTER TABLE backtest_results ADD COLUMN pattern_type TEXT;
    END IF;

    -- Check if timeframe column exists
    IF NOT EXISTS (
        SELECT FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'backtest_results'
        AND column_name = 'timeframe'
    ) THEN
        ALTER TABLE backtest_results ADD COLUMN timeframe TEXT;
    END IF;
END
$$;

-- Once the columns are added, we can create the indexes
CREATE INDEX IF NOT EXISTS idx_backtest_results_symbol ON backtest_results(symbol);
CREATE INDEX IF NOT EXISTS idx_backtest_results_timeframe ON backtest_results(timeframe);
CREATE INDEX IF NOT EXISTS idx_backtest_results_pattern_type ON backtest_results(pattern_type);

-- Create market_data_cache table if needed
CREATE TABLE IF NOT EXISTS market_data_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key TEXT NOT NULL,
    symbol TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    open DECIMAL(12,4) NOT NULL,
    high DECIMAL(12,4) NOT NULL,
    low DECIMAL(12,4) NOT NULL,
    close DECIMAL(12,4) NOT NULL,
    volume BIGINT NOT NULL,
    index INTEGER NOT NULL,
    ema7 DECIMAL(12,4),
    ema20 DECIMAL(12,4),
    ema50 DECIMAL(12,4),
    ema100 DECIMAL(12,4),
    ema200 DECIMAL(12,4),
    rsi14 DECIMAL(12,4),
    atr14 DECIMAL(12,4),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on cache_key for faster queries
CREATE INDEX IF NOT EXISTS idx_market_data_cache_key ON market_data_cache(cache_key);

-- Create market_data_metadata table
CREATE TABLE IF NOT EXISTS market_data_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key TEXT NOT NULL UNIQUE,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    source TEXT NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_delayed BOOLEAN NOT NULL DEFAULT FALSE,
    request_duration INTEGER,
    retry_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on cache_key for faster queries
CREATE INDEX IF NOT EXISTS idx_market_data_metadata_key ON market_data_metadata(cache_key);

-- Enable RLS and create policies
ALTER TABLE market_data_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_data_metadata ENABLE ROW LEVEL SECURITY;

-- Allow read access for authenticated users
CREATE POLICY IF NOT EXISTS "Allow authenticated users to read market_data_cache"
ON market_data_cache FOR SELECT
TO authenticated
USING (true);

CREATE POLICY IF NOT EXISTS "Allow authenticated users to read market_data_metadata"
ON market_data_metadata FOR SELECT
TO authenticated
USING (true); 