-- Create market_data table for storing real-time and historical market data
CREATE TABLE IF NOT EXISTS market_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    price DECIMAL(12,4) NOT NULL,
    volume BIGINT,
    bid DECIMAL(12,4),
    ask DECIMAL(12,4),
    source TEXT NOT NULL,
    data_type TEXT NOT NULL, -- 'trade', 'quote', 'aggregate'
    timeframe TEXT, -- For aggregate data
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_market_data_symbol ON market_data(symbol);
CREATE INDEX IF NOT EXISTS idx_market_data_timestamp ON market_data(timestamp);
CREATE INDEX IF NOT EXISTS idx_market_data_symbol_timestamp ON market_data(symbol, timestamp);

-- Enable Row Level Security (RLS)
ALTER TABLE market_data ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users to read data
CREATE POLICY "Allow authenticated users to read market_data"
ON market_data FOR SELECT
TO authenticated
USING (true);

-- Create policy for authenticated users to insert data
CREATE POLICY "Allow authenticated users to insert market_data"
ON market_data FOR INSERT
TO authenticated
WITH CHECK (true);

-- Create policy for authenticated users to update their own data
CREATE POLICY "Allow authenticated users to update market_data"
ON market_data FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true); 